# Generated by Django 5.0.14 on 2026-08-27 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('cpu', models.FloatField(default=0, verbose_name='CPU, %')),
                ('ram', models.FloatField(default=0, verbose_name='RAM, %')),
                ('disk', models.FloatField(default=0, verbose_name='Диск, %')),
                ('gpu', models.FloatField(blank=True, null=True, verbose_name='GPU, %')),
                ('load_avg', models.FloatField(default=0, verbose_name='Load avg')),
                ('net_sent', models.BigIntegerField(default=0, verbose_name='Сеть: отправлено, байт')),
                ('net_recv', models.BigIntegerField(default=0, verbose_name='Сеть: получено, байт')),
                ('running', models.PositiveSmallIntegerField(default=0, verbose_name='Активных задач')),
            ],
            options={
                'verbose_name': 'Метрика системы',
                'verbose_name_plural': 'Метрики системы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a', 'ogg', 'flac', 'aac', 'wma', 'opus', 'mp4', 'mkv', 'webm', 'mov', 'avi'])], verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Размер, байт')),
                ('duration_sec', models.FloatField(blank=True, null=True, verbose_name='Длительность, сек')),
                ('language', models.CharField(default='Русский', max_length=32, verbose_name='Язык')),
                ('model', models.CharField(default='large-v3-turbo', max_length=64, verbose_name='Модель')),
                ('diarization', models.BooleanField(default=True, verbose_name='Диаризация спикеров')),
                ('diarization_method', models.CharField(choices=[('ecapa', 'ecapa'), ('spectral', 'spectral')], default='spectral', max_length=32, verbose_name='Метод диаризации')),
                ('timeout_sec', models.IntegerField(default=60000, verbose_name='Таймаут (мс)')),
                ('gpu_id', models.IntegerField(default=0, verbose_name='ID GPU')),
                ('metadata_json', models.TextField(blank=True, default='', verbose_name='Метаданные JSON')),
                ('output_path', models.CharField(blank=True, default='', max_length=512, verbose_name='Путь вывода')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('done', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Инфо'), ('ok', 'Успех'), ('warn', 'Предупреждение'), ('err', 'Ошибка')], default='info', max_length=4, verbose_name='Уровень')),
                ('text', models.TextField(verbose_name='Строка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Строка журнала',
                'verbose_name_plural': 'Журналы задач',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['task', 'id'], name='core_tasklo_task_id_5d6e99_idx')],
            },
        ),
    ]
