# Generated by Django 5.0.14 on 2026-08-27 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('gazoil', 'ГазОйл'), ('eurooil', 'Евроойл'), ('callcentre', 'КоллЦентр')], max_length=32, verbose_name='Источник')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата с')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата по')),
                ('phone_filter', models.CharField(blank=True, default='', max_length=64, verbose_name='Фильтр по телефону')),
                ('department_filter', models.CharField(blank=True, default='', max_length=128, verbose_name='Фильтр по отделу')),
                ('skip_existing', models.BooleanField(default=True, verbose_name='Пропускать существующие')),
                ('min_duration_sec', models.IntegerField(default=0, verbose_name='Мин. длительность (сек)')),
                ('output_folder', models.CharField(blank=True, default='', max_length=512, verbose_name='Папка назначения')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('done', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %')),
                ('records_found', models.PositiveIntegerField(default=0, verbose_name='Найдено записей')),
                ('records_imported', models.PositiveIntegerField(default=0, verbose_name='Импортировано')),
                ('records_skipped', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('script_name', models.CharField(default='', max_length=256, verbose_name='Скрипт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задание импорта',
                'verbose_name_plural': 'Задания импорта',
                'ordering': ['-created_at'],
            },
        ),
    ]
